[package]
name = "qiita_api"
version = "0.1.0"
authors = ["Sho Sato <shsato.t.t.n@gmail.com>"]

[dependencies]
hyper = "*"
hyper-native-tls = "*"
iron = "*"
lazy_static = "*"
params = "*"
router = "*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4.2"
